---
title: Your Name
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy
  eirmod tempor invidunt ut labore et dolore magna aliquyam
about: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
  tempor invidunt ut labore et dolore magna aliquyam
location: Your Region, Country
email: your-email@example.com
baseurl: 
url: http://testlearn.siteleaf.net
twitter_username: your-name
github_username: your-name
g_analytics: 
isolang: en
close_btn: Close
home_btn: Home
projects_btn: Projects
posts_btn: Posts
imprint_btn: Imprint
name_badge: an article by
rss_badge: Subscribe feed!
markdown: kramdown
exclude:
- LICENSE
- README.md
